# Generated by Django 4.1.6 on 2023-02-06 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nct_id', models.CharField(max_length=50, verbose_name='임상연구 번호')),
                ('results_first_submitted_date', models.DateField(verbose_name='최초 제출 날짜')),
                ('last_update_submitted_date', models.DateField(verbose_name='최근 수정 날짜')),
                ('start_date', models.DateField(verbose_name='임상연구 시작 날짜')),
                ('completion_date', models.DateField(verbose_name='임상연구 종료 날짜')),
                ('title', models.CharField(max_length=300, verbose_name='제목')),
                ('overall_status', models.CharField(max_length=50, verbose_name='진행 상태')),
                ('phase', models.CharField(max_length=50, verbose_name='임상 단계')),
                ('enrollment', models.IntegerField(verbose_name='대상자 수')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_type', models.CharField(max_length=50, verbose_name='치료 타입')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.study')),
            ],
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampling_method', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10, verbose_name='성별')),
                ('minimum_age', models.CharField(max_length=30, verbose_name='최소 나이')),
                ('maximum_age', models.CharField(max_length=30, verbose_name='최대 나이')),
                ('healthy_volunteers', models.CharField(max_length=100)),
                ('population', models.TextField()),
                ('criteria', models.TextField()),
                ('gender_description', models.TextField()),
                ('gender_based', models.TextField()),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.study')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('studies', models.ManyToManyField(related_name='conditions', to='studies.study')),
            ],
        ),
    ]
