# Generated by Django 4.1.6 on 2023-02-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eligibility',
            name='gender_based',
        ),
        migrations.RemoveField(
            model_name='eligibility',
            name='gender_description',
        ),
        migrations.RemoveField(
            model_name='eligibility',
            name='population',
        ),
        migrations.RemoveField(
            model_name='eligibility',
            name='sampling_method',
        ),
    ]
