# Generated by Django 4.1.6 on 2023-02-14 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_remove_eligibility_gender_based_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibility',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibilities', to='studies.study'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='studies.study'),
        ),
    ]
