# Generated by Django 4.1.6 on 2023-02-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_alter_eligibility_study_alter_intervention_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='healthy_volunteers',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='maximum_age',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='최대 나이'),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='minimum_age',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='최소 나이'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='intervention_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='치료 타입'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='임상연구 종료 날짜'),
        ),
        migrations.AlterField(
            model_name='study',
            name='enrollment',
            field=models.IntegerField(blank=True, null=True, verbose_name='대상자 수'),
        ),
        migrations.AlterField(
            model_name='study',
            name='last_update_submitted_date',
            field=models.DateField(blank=True, null=True, verbose_name='최근 수정 날짜'),
        ),
        migrations.AlterField(
            model_name='study',
            name='nct_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='임상연구 번호'),
        ),
        migrations.AlterField(
            model_name='study',
            name='overall_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='진행 상태'),
        ),
        migrations.AlterField(
            model_name='study',
            name='phase',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='임상 단계'),
        ),
        migrations.AlterField(
            model_name='study',
            name='results_first_submitted_date',
            field=models.DateField(blank=True, null=True, verbose_name='최초 제출 날짜'),
        ),
        migrations.AlterField(
            model_name='study',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='임상연구 시작 날짜'),
        ),
        migrations.AlterField(
            model_name='study',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='제목'),
        ),
    ]
