# Generated by Django 4.1.6 on 2023-02-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_alter_condition_name_alter_eligibility_criteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
