# Generated by Django 4.1.6 on 2023-02-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_alter_intervention_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='제목'),
        ),
    ]
