# Generated by Django 4.1.6 on 2023-02-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0006_alter_study_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='변수명')),
                ('value', models.CharField(max_length=100, verbose_name='값')),
            ],
        ),
    ]
