# Generated by Django 4.1.6 on 2023-02-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0009_alter_condition_name_alter_eligibility_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='control_status_type',
            field=models.CharField(blank=True, choices=[(20, 'CONVERT_READY'), (50, 'TRANSLATE_READY'), (100, 'COMPLETED')], max_length=50, null=True, verbose_name='임상연구 적재 상태'),
        ),
        migrations.AddField(
            model_name='study',
            name='original_data',
            field=models.TextField(blank=True, null=True, verbose_name='원본 데이터'),
        ),
    ]
